In [1]:
print ("hello world!!!")

hello world!!!


In [2]:
import numpy as np

In [3]:
print(np.__version__)
np.show_config()

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/git/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/git/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/git/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/git/Anaconda3\\Lib

In [4]:
#创建一个长度为10的空向量
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#4、如何找到任何一个数组的内存大小
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [12]:
#5、如何从命令行得到numpy中add函数的说明文档？
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [8]:
#5、如何从命令行得到numpy中add函数的说明文档？
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [9]:
#6、创建一个长度为10，并且除了第五个值为1的空向量
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [11]:
#7、创建一个值域范围从10到49的向量
Z = np.arange(10,25)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [13]:
#8、反转一个向量（第一个元素变成最后一个）
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [14]:
#9、创建一个3x3并且值从0到8的矩阵
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
#10、找到数组[1,2,0,0,4,0]中非0元素的位置索引
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [16]:
#11、创建一个3x3的单位矩阵
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#12、创建一个3x3x3的随机数组
Z = np.random.random((3,3,3))
print(Z)

[[[0.73756714 0.44354324 0.04247617]
  [0.0548609  0.12565941 0.78540024]
  [0.56808781 0.41288418 0.41175763]]

 [[0.66693843 0.03641135 0.10969435]
  [0.32897413 0.09876896 0.33543283]
  [0.03724297 0.0191323  0.80880197]]

 [[0.22274798 0.96673667 0.61386672]
  [0.9176043  0.62873958 0.40756436]
  [0.40546496 0.32215582 0.66210467]]]


In [19]:
#13、创建一个10x10的随机数组并找到它的最大值和最小值
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.0011655868365467725 0.9848464315563931


In [20]:
#14、创建一个额长度为30的随机向量，并找到他的平均值
Z = np.random.random(30)
m = Z.mean()
print(m)

0.5857478583381878


In [21]:
#15、创建一个二维数组，其中边界值是1，其余值为0
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [23]:
#16、对于一个存在的数组，如何添加一个用0填充的边界
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [25]:
#17-1、以下表达式运行结果分别是什么？
print(0 * np.nan)

nan


In [26]:
#17-2、以下表达式运行结果分别是什么？
print(np.nan == np.nan)

False


In [27]:
#17-3、以下表达式运行结果分别是什么？
print(np.inf > np.nan)

False


In [28]:
#17-4、以下表达式运行结果分别是什么？
print(np.nan - np.nan)

nan


In [29]:
#17-5、以下表达式运行结果分别是什么？
print(0.3 == 3 * 0.1)

False


In [30]:
#18、创建一个5x5的矩阵，并设置1,2,3,4落在其对角线下方位置
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [31]:
#19、创建一个8x8的矩阵，并且设置成棋盘样式
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [32]:
#20、考虑一个（6,7,8）形状的数组，其第100各元素的索引（x,y,z）是什么
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [35]:
#21、用title函数去创建一个8x8的棋盘样式矩阵
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [36]:
#22、对一个5x5的随机矩阵做归一化
Z = np.random.random((5,5))
Zmax,Zmin = Z.max(), Z.min()
Z = (Z-Zmin)/(Zmax-Zmin)
print(Z)

[[0.64478811 0.         0.71829684 0.75474933 0.27077523]
 [0.95277479 0.54638733 0.10788181 0.59000333 0.41341561]
 [0.72855834 0.57862282 0.95759244 0.36528366 1.        ]
 [0.42360137 0.36417886 0.53805287 0.10368389 0.9903965 ]
 [0.90588524 0.78718272 0.34502376 0.30714556 0.50877647]]


In [37]:
#23、创建一个将颜色描述为（RGBA）四个无符号字节的自定义dtype？
color = np.dtype([("r", np.ubyte, 1), 
                  ("g", np.ubyte, 1), 
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [38]:
#24、一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [39]:
#25、给定一个一维数组，对其在3到8之间的所有元素取反(取负数)
Z = np.arange(11)
Z[(3<Z) & (Z<=8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [40]:
#26-1、下面脚本运行后的结果是什么？
print(sum(range(5), -1))

9


In [41]:
#26-2、下面脚本运行后的结果是什么？
from numpy import *
print(sum(range(5), -1))

10


In [42]:
#27-1、考虑一个整数向量Z，下列表达合法的是那个？
Z = np.arange(5)
Z ** Z 
#legal

array([  1,   1,   4,  27, 256], dtype=int32)

In [53]:
#27-2、考虑一个整数向量Z，下列表达合法的是那个？
Z = np.arange(5)
2 << Z >> 2 
#false

array([0, 1, 2, 4, 8], dtype=int32)

In [44]:
#27-3、考虑一个整数向量Z，下列表达合法的是那个？
Z = np.arange(5)
Z <- Z
#legal

array([False, False, False, False, False])

In [49]:
#27-4、考虑一个整数向量Z，下列表达合法的是那个？
Z = np.arange(5)
1j*Z
#legal

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [50]:
#27-5、考虑一个整数向量Z，下列表达合法的是那个？
Z = np.arange(5)
Z/1/1
#legal

array([0., 1., 2., 3., 4.])

In [52]:
#27-6、考虑一个整数向量Z，下列表达合法的是那个？
Z = np.arange(5)
Z          #Z<Z>Z 
#false

array([0, 1, 2, 3, 4])

In [54]:
#28-1、下列表达式的结果分别是什么？
print(np.array(0) / np.array(0))

nan


D:\git\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


In [55]:
#28-2、下列表达式的结果分别是什么？
print(np.array(0) // np.array(0))

0


D:\git\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


In [56]:
#28-3、下列表达式的结果分别是什么？
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


In [57]:
#29、如何从零位对浮点数组做舍入？
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[ -4.   3.  -9.   5.  10.  -7.  -2.   4. -10.  -9.]


In [60]:
#30、如何找到两个数组中的共同元素，是数字1
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 1 5 9]


In [63]:
#31、如何忽略所有的numpy警告（尽管不建议这样做）
#Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1)/0

#Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:
    Z = np.ones(1)/0
    
#不太清楚此处代码的含义

In [64]:
#32、下面表达式是正确的么？
np.sqrt(-1) == np.emath.sqrt(-1)
#false

D:\git\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [65]:
#33、如何得到昨天、今天、明天的日期？
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-06-20
Today is 2019-06-21
Tomorrow is 2019-06-22


In [66]:
#34、如何得到所有与2016年7月对应的日期
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [67]:
#35-1、如何直接在位计算(A+B)\*(-A/2)(不建立副本)
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)

array([3., 3., 3.])

In [68]:
np.divide(A,2,out=A)

array([0.5, 0.5, 0.5])

In [69]:
np.negative(A, out=A)

array([-0.5, -0.5, -0.5])

In [70]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [72]:
#36-1、用五种不同的方法去提取一个随机数组的整数部分
Z = np.random.uniform(0,10,10)
print(Z - Z%1)

[7. 0. 8. 2. 1. 0. 0. 7. 5. 6.]


In [73]:
#36-2、用五种不同的方法去提取一个随机数组的整数部分
print(np.floor(Z))

[7. 0. 8. 2. 1. 0. 0. 7. 5. 6.]


In [74]:
#36-3、用五种不同的方法去提取一个随机数组的整数部分
print(np.ceil(Z)-1)

[7. 0. 8. 2. 1. 0. 0. 7. 5. 6.]


In [75]:
#36-4、用五种不同的方法去提取一个随机数组的整数部分
print(Z.astype(int))

[7 0 8 2 1 0 0 7 5 6]


In [76]:
#36-5、用五种不同的方法去提取一个随机数组的整数部分
print(np.trunc(Z))

[7. 0. 8. 2. 1. 0. 0. 7. 5. 6.]


In [77]:
#37、创建一个5x5的矩阵，其中每行的数值范围从0到4
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [79]:
#38、通过一个可生成10个整数的函数，来构建一个数组
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [81]:
#39、创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [82]:
#40、创建一个长度为10的随机向量，并将其排序
Z = np.random.random(10)
Z.sort()
print(Z)

[0.15393156 0.16518041 0.21338812 0.2260282  0.35475689 0.49085341
 0.53257454 0.59824554 0.64087661 0.93622834]


In [83]:
#41、对于一个小数组，如何用比np.sum更快的方式对其求和
Z = np.arange(10)
np.add.reduce(Z)

45

In [85]:
#42-1、对于两个随机数组A和B，检查他们是否相等
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [87]:
print("hahah")

hahah


In [88]:
#42-2、对于两个随机数组A和B，检查他们是否相等
equal = np.array_equal(A,B)
print(equal)

False


In [89]:
#43、创建一个只读数组（read-only）
Z = np.zeros(10)
Z.flags.writeable = False
Z[0]=1

ValueError: assignment destination is read-only

In [90]:
#44、将笛卡尔坐标下的一个10x2的矩阵转换成极坐标形式
Z = np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.20849026 0.52444226 0.83666865 0.53726575 0.9757834  0.75491228
 1.16175362 0.88314881 0.88471431 1.10467465]
[0.84148868 0.71514012 0.2055119  0.94306203 1.15319016 0.19843909
 0.90804728 0.65802541 0.50512447 0.53315169]


In [2]:
#45、创建一个长度为10的向量，并将向量中最大值替换为1
import numpy as np
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.04030433 0.         0.81272864 0.38410634 0.62193631 0.89602331
 0.78504319 0.82424554 0.22008387 0.52465788]


In [3]:
#46、创建一个结构化数组，并实现x和y坐标覆盖[0,1]x[0,1]区域
Z = np.zeros((5,5), [('x', float),('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [4]:
#47、给定两个数组X和Y，构造Cauchy矩阵C(Cij = 1/(xi-yj))
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X,Y)
print(np.linalg.det(C))

3638.1636371179666


In [10]:
#48、打印每个numpy标量类型的最小值和最大值
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [14]:
#49、如何打印一个数组中的所有数值
#np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [15]:
#50、给定标量时，如何找到数组中最接近标量的值
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v).argmin())
print (Z[index])

2


In [18]:
#51、创建一个表示位置（x，y）和颜色（r，g，b）的结构化数组
Z = np.zeros(10,[('position', [('x', float, 1),
                               ('y', float,1)]),
                ('color', [('r', float, 1),
                           ('g', float, 1), 
                           ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [19]:
#52-1、对一个表示坐标形状为（100,2）的随机向量，找到点与点的距离
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.54037814 0.54681817 0.41697865 0.77389689 0.45338544
  0.50074548 0.20803121 0.60364551 0.524361  ]
 [0.54037814 0.         0.78326588 0.2685468  0.50409617 0.4928308
  0.10242847 0.33413864 0.33825291 0.26326923]
 [0.54681817 0.78326588 0.         0.84241997 1.21274563 0.96833234
  0.68651177 0.57227386 1.02541315 0.56479013]
 [0.41697865 0.2685468  0.84241997 0.         0.37407245 0.22497053
  0.32011596 0.27395294 0.19118878 0.46372098]
 [0.77389689 0.50409617 1.21274563 0.37407245 0.         0.37161833
  0.60011702 0.64793993 0.18751101 0.76350769]
 [0.45338544 0.4928308  0.96833234 0.22497053 0.37161833 0.
  0.54252298 0.40975206 0.27073821 0.67661937]
 [0.50074548 0.10242847 0.68651177 0.32011596 0.60011702 0.54252298
  0.         0.29381399 0.42664926 0.16347061]
 [0.20803121 0.33413864 0.57227386 0.27395294 0.64793993 0.40975206
  0.29381399 0.         0.46315687 0.3419408 ]
 [0.60364551 0.33825291 1.02541315 0.19118878 0.18751101 0.27073821
  0.42664926 0.463156

In [20]:
#52-2、对一个表示坐标形状为（100,2）的随机向量，找到点与点的距离
import scipy
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.54037814 0.54681817 0.41697865 0.77389689 0.45338544
  0.50074548 0.20803121 0.60364551 0.524361  ]
 [0.54037814 0.         0.78326588 0.2685468  0.50409617 0.4928308
  0.10242847 0.33413864 0.33825291 0.26326923]
 [0.54681817 0.78326588 0.         0.84241997 1.21274563 0.96833234
  0.68651177 0.57227386 1.02541315 0.56479013]
 [0.41697865 0.2685468  0.84241997 0.         0.37407245 0.22497053
  0.32011596 0.27395294 0.19118878 0.46372098]
 [0.77389689 0.50409617 1.21274563 0.37407245 0.         0.37161833
  0.60011702 0.64793993 0.18751101 0.76350769]
 [0.45338544 0.4928308  0.96833234 0.22497053 0.37161833 0.
  0.54252298 0.40975206 0.27073821 0.67661937]
 [0.50074548 0.10242847 0.68651177 0.32011596 0.60011702 0.54252298
  0.         0.29381399 0.42664926 0.16347061]
 [0.20803121 0.33413864 0.57227386 0.27395294 0.64793993 0.40975206
  0.29381399 0.         0.46315687 0.3419408 ]
 [0.60364551 0.33825291 1.02541315 0.19118878 0.18751101 0.27073821
  0.42664926 0.463156

In [21]:
#53、如何将32位浮点数（float）转化成对应的整数（integer）
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [23]:
#54、如何读取以下文件
#55、对于numpy数组，enumerate的等价操作是什么
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index,Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [24]:
#56、生成一个通用的二维Gaussian-like数组
X,Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0,0.0
G = np.exp(-((D-mu)**2 / (2.0 * sigma**2 )))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [25]:
#57、对一个二维数组，如何在其内部随机放置p个元素
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [2]:
#58-1、减去一个矩阵中的每一行的平均值
import numpy as np
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1,keepdims=True)
print(Y)

[[-0.02931915 -0.23612849  0.23530035 -0.48922374 -0.50624271  0.39786933
  -0.16856897  0.15579532  0.33144132  0.30907672]
 [ 0.16597263 -0.31264817 -0.345387   -0.25383444  0.42984103 -0.43736818
   0.39714269  0.41932828 -0.05909884 -0.00394799]
 [ 0.48590733  0.45074104 -0.0369014  -0.05925886 -0.06405748  0.17649028
  -0.31273559 -0.31163596 -0.3540483   0.02549893]
 [-0.00791475  0.16561471 -0.18498766  0.48016713  0.15342166 -0.37985854
   0.07162789  0.14576662 -0.35445045 -0.0893866 ]
 [-0.2439242  -0.42732876  0.40553042  0.14526141  0.03423515 -0.43398531
   0.42442975  0.33504585 -0.49926744  0.26000313]]


In [3]:
#58-2、减去一个矩阵中的每一行的平均值
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1).reshape(-1,1)
print(Y)

[[ 0.25830265 -0.0487032  -0.10840293 -0.49766784  0.36483154  0.01224584
  -0.00870851  0.20484203  0.3828125  -0.55955209]
 [ 0.23632975 -0.40377294 -0.35538515  0.06422805  0.12968176  0.2480323
   0.41964686 -0.3632154   0.45381014 -0.42935538]
 [-0.23704596 -0.53429243  0.22946194 -0.02671197  0.18011024  0.26409657
   0.22977399  0.0781611  -0.28117867  0.09762521]
 [-0.39058023 -0.25881023  0.41049257 -0.10543404  0.15223103  0.41203949
   0.19743196  0.11846418 -0.11990269 -0.41593204]
 [ 0.36527113  0.29927716 -0.17143468 -0.5875066  -0.61384387  0.18789119
   0.04829213  0.25647983 -0.06412003  0.27969374]]


In [4]:
#59、如何通过后台第n列对一个数组进行排序排序 
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 9 4]
 [5 5 5]
 [4 0 6]]
[[4 0 6]
 [5 5 5]
 [2 9 4]]


In [6]:
#60、如何检查一个二维数组是否有空列
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


In [8]:
#61、从数组中的给定值中找出最近的值
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z-z).argmin()]
print(m)

0.553569385417081


In [4]:
#62、如何使用迭代器Iterator，计算两个分别具有形状（1,3）和（3,1）的数组
import numpy as np
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it:
    z[...] = x+y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [9]:
#63、创建一个具有name属性的数组类
class NamedArray(np.ndarray):
    def __new__(cls,array,name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self,obj):
        if obj is None: return
        self.info = getattr(obj,'name',"no name")
    
Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


In [10]:
#64-1、考虑一个给定的向量，如何对由第二个向量索引的每个元素加1（小心重复的索引）
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I,minlength=len(Z))
print(Z)

[3. 2. 4. 2. 5. 3. 3. 4. 3. 1.]


In [12]:
#64-2、
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
np.add.at(Z,I,1)
print(Z)

[3. 2. 3. 5. 2. 3. 4. 1. 5. 2.]


In [13]:
#65、根据索引列表（I）如何将向量X的元素累加到数组F
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [14]:
#66、考虑一个dtype=ubyte的（v,h,3）图像，计算其唯一颜色的数量
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 + I[...,2]
n = len(np.unique(F))
print(n)

8


In [15]:
#67-1、考虑一个四维数组，如何一次性计算出最后两个轴axis的和？
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[64 48 40 73]
 [48 65 65 53]
 [64 48 53 62]]


In [16]:
#67-2、
A = np.random.randint(0,10,(3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[42 40 52 34]
 [78 55 44 49]
 [60 62 62 63]]


In [17]:
#68-1、考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.43359865 0.58126245 0.59662447 0.57848347 0.55590797 0.5865165
 0.60191238 0.37702036 0.41663639 0.49511848]


In [18]:
#68-2、
import pandas as pd
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print(pd.Series(D).groupby(S).mean())

0    0.520996
1    0.379036
2    0.464967
3    0.583509
4    0.502238
5    0.428226
6    0.550832
7    0.502225
8    0.445889
9    0.495046
dtype: float64


In [20]:
#69-1、如何获得点积dot product的对角线
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A,B))

array([1.73103542, 0.56667001, 1.64009581, 0.92075014, 1.94139769])

In [21]:
#69-2、
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.sum(A * B.T, axis=1)

array([1.13461663, 1.12808653, 2.28654622, 2.10613823, 1.60931998])

In [23]:
#69-3、
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.einsum("ij,ji->i", A, B)

array([0.45788217, 1.89466165, 1.44754843, 1.32966618, 1.10442212])

In [ ]:
#70、考虑

In [24]:
#70、考虑一个向量[1,2,3,4,5]如何建立一个新的向量，在这个新向量中每个值之间有3个连续的0
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [26]:
#71、考虑一个维度（5,5,3）的数组，如何将其与一个（5,5）的数组相乘
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A*B[:, :, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [27]:
#72、如何对一个数组中任意两行作交换
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [29]:
#73、考虑一个可以描述10个三角形的triplets，找到可 的以分割全部lines segment
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view(dtype=[('p0',F.dtype),('pt',F.dtype)])
G = np.unique(G)
print(G)

[( 5, 19) ( 5, 75) ( 8, 71) ( 8, 88) (12, 21) (12, 43) (15, 24) (15, 30)
 (16, 48) (16, 51) (16, 83) (16, 96) (19, 75) (21, 34) (21, 43) (21, 53)
 (24, 30) (29, 46) (29, 53) (34, 53) (35, 47) (35, 53) (46, 53) (47, 53)
 (48, 51) (51, 62) (51, 86) (62, 86) (71, 88) (83, 96)]


In [30]:
#74、给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)=C
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(A)

[1 1 2 3 4 4 6]


In [31]:
#75、如何通过滑动窗口计算一个数组的额平均值
def moving_average(a,n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] /n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [32]:
#76、
from numpy.lib import stride_tricks
def rolling(a,window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a,shape=shape,strides=strides)
Z = rolling(np.arange(10),3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [34]:
#77-1、如何对布尔值取反，或者原位in-place改变浮点数的符号sign
Z = np.random.randint(0,2,100)
np.logical_not(Z,out=Z)

array([0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0])

In [37]:
#77-2、
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.17567416,  0.49867921,  0.45936945,  0.30945508,  0.53197357,
        0.74706123, -0.33136624,  0.221245  ,  0.5215681 ,  0.51960492,
       -0.77069002, -0.24047426, -0.78585632,  0.12073899, -0.65533363,
        0.65460666, -0.35005168, -0.54855166,  0.87694331,  0.35528866,
        0.11587053, -0.75903998, -0.26477185, -0.23364792,  0.5735859 ,
       -0.99751617,  0.75474602,  0.16276545, -0.96365976,  0.20257708,
        0.85338746, -0.74019161,  0.69331925,  0.4142953 , -0.34328922,
        0.86683603, -0.86760123, -0.15744318, -0.93846178, -0.4668215 ,
       -0.51672764, -0.7144875 ,  0.08068035, -0.06670901,  0.30315084,
       -0.33193831, -0.44693013,  0.23073287, -0.77598527, -0.56991125,
        0.60338296,  0.70713594, -0.83148529, -0.43579859, -0.02894772,
        0.5050578 ,  0.13003907,  0.4602273 ,  0.52364101, -0.6529413 ,
        0.95186222, -0.22335725, -0.7152786 , -0.88524325, -0.3073258 ,
        0.62102571,  0.76473447,  0.10598436,  0.01274656,  0.38

In [42]:
#78、考虑两组点集P0和P1去描述一组线（二维）和一个点p，如何计算点p到每一条线i（p0[i],p1[i]）的距离
def distance(p0, p1, p):
    T = p1 - p0
    L = (T**2).sum(axis=1)
    U = -((p0[:,0]-p[...,0])*T[:,0] + (p0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = p0 + U*T - p
    return np.sqrt(D**2).sum(axis=1)

p0 = np.random.uniform(-10,10,(10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(1,2))

print(distance(p0,p1,p))

[ 8.9009738  13.67012213 24.5051011  16.43389867 25.97291257  1.54027601
  3.12453692 12.65153908  8.66729096 19.1218496 ]


In [43]:
#79、考虑两组点集p0和p1去描述一组线（二维）和一组点集p，如何计算每一个点j(p[j])到每一条线i(p0[i],p1[i])的距离
p0 = np.random.uniform(-10,10,(10,2))
p1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(10,2))
print(np.array([distance(p0,p1,p_i) for p_i in p]))

[[ 8.12930469  5.38771074  6.54229866  6.70896676  1.60178167 12.55719288
   5.22239424 13.1103878  17.14706615 14.78394022]
 [ 9.86314153  6.54166297  5.64018878  8.70057131  0.5061174  11.76884404
   6.24496639 11.12924005 16.82969696 13.53279053]
 [ 1.62176909  4.91445863  4.62541552  1.62604012  8.55102961  0.71584795
   4.8949401  13.65112285  3.62562379  7.18106702]
 [ 5.52652863  7.98104578  4.58659203  5.75968535 12.69629514  0.4943189
   7.73362922 16.81206785  2.46226424  8.20250859]
 [ 6.56839679  9.31623484  6.77856225  6.47402454 13.13713493  1.7717074
   9.08313988 16.21792956  0.07629402  6.48993355]
 [ 9.94623193  1.22131485 17.30404037 12.83688839  7.52424186 11.21765006
   0.13708679  3.91403186  4.76832328  7.16946886]
 [17.57735927  9.46142196  7.80725054 19.22623696 12.73402844  1.19210384
   8.25836749  3.84307987  6.52690543  0.53716338]
 [ 0.58886282  7.96954192 25.05853586  4.31571196  0.03917637 19.61240579
   8.77534248  1.46151556 14.95202553 11.79522525]
 [

In [48]:
#80、

Z = np.random.randint(0,10,(10,10)) 
shape = (5,5)
fill = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start,(R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)


[[9 8 2 3 8 9 1 3 5 6]
 [5 6 7 7 7 4 7 2 2 3]
 [6 3 7 4 4 4 3 7 3 1]
 [2 4 7 7 1 2 4 8 5 6]
 [6 8 7 7 9 7 1 7 3 8]
 [5 9 3 2 9 2 5 4 6 9]
 [2 6 8 7 5 4 7 4 7 7]
 [7 9 9 9 9 3 9 6 7 6]
 [7 8 0 9 0 4 3 2 6 4]
 [5 2 7 3 1 2 8 9 9 4]]
[[0 0 0 0 0]
 [0 9 8 2 3]
 [0 5 6 7 7]
 [0 6 3 7 4]
 [0 2 4 7 7]]


D:\git\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [49]:
#81、简言之，就是把数组分开
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [3]:
#82、计算一个矩阵的秩
import numpy as np
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


In [4]:
#83、如何找到一个数组中出现频率最高的值
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

7


In [11]:
#84、从一个10x10的矩阵中提取出连续的3x3区块
#注意这个地方C的那个地方（np.lib）
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 3 1]
   [4 0 3]
   [2 0 0]]

  [[3 1 1]
   [0 3 2]
   [0 0 2]]

  [[1 1 0]
   [3 2 2]
   [0 2 4]]

  [[1 0 4]
   [2 2 4]
   [2 4 3]]

  [[0 4 1]
   [2 4 4]
   [4 3 1]]

  [[4 1 1]
   [4 4 0]
   [3 1 0]]

  [[1 1 2]
   [4 0 2]
   [1 0 0]]

  [[1 2 0]
   [0 2 2]
   [0 0 2]]]


 [[[4 0 3]
   [2 0 0]
   [2 4 1]]

  [[0 3 2]
   [0 0 2]
   [4 1 0]]

  [[3 2 2]
   [0 2 4]
   [1 0 2]]

  [[2 2 4]
   [2 4 3]
   [0 2 4]]

  [[2 4 4]
   [4 3 1]
   [2 4 4]]

  [[4 4 0]
   [3 1 0]
   [4 4 2]]

  [[4 0 2]
   [1 0 0]
   [4 2 4]]

  [[0 2 2]
   [0 0 2]
   [2 4 2]]]


 [[[2 0 0]
   [2 4 1]
   [4 0 3]]

  [[0 0 2]
   [4 1 0]
   [0 3 2]]

  [[0 2 4]
   [1 0 2]
   [3 2 3]]

  [[2 4 3]
   [0 2 4]
   [2 3 3]]

  [[4 3 1]
   [2 4 4]
   [3 3 1]]

  [[3 1 0]
   [4 4 2]
   [3 1 3]]

  [[1 0 0]
   [4 2 4]
   [1 3 4]]

  [[0 0 2]
   [2 4 2]
   [3 4 1]]]


 [[[2 4 1]
   [4 0 3]
   [4 4 3]]

  [[4 1 0]
   [0 3 2]
   [4 3 1]]

  [[1 0 2]
   [3 2 3]
   [3 1 1]]

  [[0 2 4]
   [2 3 3]
   [1 1 4]]

  [[2 4 4]
   

In [22]:
#85、创满足z[i,j]==z[j,i]的子类
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 3  5 14  6 17]
 [ 5  4 12 10  5]
 [14 12  5 42 14]
 [ 6 10 42  1  5]
 [17  5 14  5  4]]


In [25]:
#86、考虑p个n*n矩阵和一组形状为（n，1）的向量，如何计算p个矩阵的乘积
p,n = 10,20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M,V,axes=[[0,2],[0,1]])
print(S)

    

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [30]:
#87、对于一个16x16的数组，如何得到一个区域（block-sum）的和（区域大小为4*4）
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0],k), axis=0),
                   np.arange(0, Z.shape[1],k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [34]:
#88、如何利用numpy数组实现Game of Life
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] + 
        Z[1:-1,0:-2] + Z[1:-1,2:] + Z[2: ,0:-2] + 
        Z[2: ,1:-1] + Z[2: ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [35]:
#89-1、如何找到一个数组的第n个最大值
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


In [36]:
#89-2、
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])

[9997 9999 9996 9998 9995]


In [38]:
#90、给定任意个数向量，创建笛卡尔（每一个元素的每一种组合）
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1,2,3],[4,5],[6,7])))
    

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [40]:
#91、如何从一个正常数组创建记录数组（record array）
Z = np.array([("Hello", 2.5, 3),
             ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                              formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [41]:
#92-1、考虑一个大向量Z，用三种不同的方法计算它的立方
x = np.random.rand()
np.power(x,3)

0.18527614544392634

In [42]:
#92-2
x*x*x

0.18527614544392634

In [45]:
#93、如何在数组A中找到满足包含B中元素的行
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[3]


In [46]:
#94-1、考虑一个10x3的矩阵，分解出不全相同值的行
Z = np.random.randint(0,5,(10,3))
print (Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[0 2 4]
 [2 0 3]
 [3 0 2]
 [4 2 2]
 [1 1 3]
 [1 1 2]
 [2 1 3]
 [1 3 0]
 [0 2 1]
 [2 4 4]]
[[0 2 4]
 [2 0 3]
 [3 0 2]
 [4 2 2]
 [1 1 3]
 [1 1 2]
 [2 1 3]
 [1 3 0]
 [0 2 1]
 [2 4 4]]


In [47]:
#94-2、
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print (U)

[[0 2 4]
 [2 0 3]
 [3 0 2]
 [4 2 2]
 [1 1 3]
 [1 1 2]
 [2 1 3]
 [1 3 0]
 [0 2 1]
 [2 4 4]]


In [48]:
#95-1、讲一个整数向量转换为matrix binary的表现形式
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [53]:
#96、给定一个二维数组，如何提取出唯一的unique行
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 1]]


In [55]:
#97-1、考虑两个向量A和B，写出用enisum等式对应的inner、outer、sum、mul函数
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))

sum
6.7728151418370865


In [56]:
#97-2、
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('A*B')
print (np.einsum('i,i->i', A, B))

A*B
[0.18389935 0.6276319  0.14807184 0.60183495 0.06908811 0.02441058
 0.23125292 0.28189912 0.45735834 0.22390112]


In [57]:
#97-3、
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('inner')
print (np.einsum('i,i', A, B))

inner
3.418110400474914


In [58]:
#97-4、
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('outer')
print (np.einsum('i,j->ij', A, B))

outer
[[0.0270803  0.01534021 0.0280354  0.04747831 0.00995698 0.04342987
  0.09835325 0.062493   0.00563334 0.01091078]
 [0.10038855 0.05686721 0.10392916 0.17600539 0.03691122 0.16099755
  0.36460231 0.2316659  0.02088319 0.04044703]
 [0.0054288  0.00307526 0.00562027 0.00951801 0.00199608 0.00870641
  0.01971694 0.01252801 0.00112932 0.00218729]
 [0.25291862 0.14327107 0.26183881 0.44342746 0.09299402 0.40561676
  0.91857799 0.58365839 0.05261304 0.10190213]
 [0.05384319 0.03050061 0.05574218 0.09440012 0.01979726 0.0863507
  0.19555368 0.12425352 0.01120065 0.02169368]
 [0.20533103 0.11631409 0.21257286 0.35999492 0.07549685 0.32929845
  0.74574411 0.47384088 0.0427137  0.08272886]
 [0.0935799  0.0530103  0.09688037 0.16406817 0.03440779 0.15007822
  0.33987389 0.21595362 0.01946683 0.03770379]
 [0.03185167 0.01804305 0.03297505 0.05584367 0.01171134 0.05108193
  0.11568244 0.07350386 0.0066259  0.01283319]
 [0.03123215 0.01769211 0.03233368 0.0547575  0.01148355 0.05008838
  0.113

In [60]:
#98、用等距样例进行采样
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.cos(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr) 
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)

In [61]:
#99、
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


In [62]:
#100、对一个一维数组X，计算它boostrapped之后的95%置信区间的平均值
X = np.random.randn(100)
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)

[-0.13616156  0.23971301]
